### PR TITLE
Updates tcl/tk to 8.6.12

### PR DESCRIPTION
**Pull request by aniedzielaAnaconda**
Changelog: https://wiki.tcl-lang.org/page/Changes+in+Tcl%2FTk+8.6.12

### CODE REVIEW

**Review by tobijk — CHANGES_REQUESTED** [review]
The license is not an SPDX identifier, can you fix that? Probably need to adjust license family, as well.

**Review by tobijk — APPROVED** [review]
Otherwise looks good to me.

**Comment by aniedzielaAnaconda** [comment]
@skupr-anaconda The proper identifier for the [TCL/TK License](https://spdx.org/licenses/TCL.html) is TCL. So you are suggesting that the `license` field to be `LicenseRef-TCL`?

@tobijk @katietz +1

**Comment by skupr-anaconda** [comment]
Ah, TCL is correct https://spdx.org/licenses/

**Review by skupr-anaconda — APPROVED** [review]

**Pull request merged**
